package com.springboot_mybatis.wx_uax.entity;

public class news {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NewsID
     *
     * @mbggenerated
     */
    private Integer newsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NewsImage
     *
     * @mbggenerated
     */
    private String newsimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NewsTitle
     *
     * @mbggenerated
     */
    private String newstitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.ReadCount
     *
     * @mbggenerated
     */
    private Integer readcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NewsContent
     *
     * @mbggenerated
     */
    private String newscontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NewsID
     *
     * @return the value of news.NewsID
     *
     * @mbggenerated
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NewsID
     *
     * @param newsid the value for news.NewsID
     *
     * @mbggenerated
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NewsImage
     *
     * @return the value of news.NewsImage
     *
     * @mbggenerated
     */
    public String getNewsimage() {
        return newsimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NewsImage
     *
     * @param newsimage the value for news.NewsImage
     *
     * @mbggenerated
     */
    public void setNewsimage(String newsimage) {
        this.newsimage = newsimage == null ? null : newsimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NewsTitle
     *
     * @return the value of news.NewsTitle
     *
     * @mbggenerated
     */
    public String getNewstitle() {
        return newstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NewsTitle
     *
     * @param newstitle the value for news.NewsTitle
     *
     * @mbggenerated
     */
    public void setNewstitle(String newstitle) {
        this.newstitle = newstitle == null ? null : newstitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.ReadCount
     *
     * @return the value of news.ReadCount
     *
     * @mbggenerated
     */
    public Integer getReadcount() {
        return readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.ReadCount
     *
     * @param readcount the value for news.ReadCount
     *
     * @mbggenerated
     */
    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NewsContent
     *
     * @return the value of news.NewsContent
     *
     * @mbggenerated
     */
    public String getNewscontent() {
        return newscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NewsContent
     *
     * @param newscontent the value for news.NewsContent
     *
     * @mbggenerated
     */
    public void setNewscontent(String newscontent) {
        this.newscontent = newscontent == null ? null : newscontent.trim();
    }
}